# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - install
  - test

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

InstallRequirements:
  stage: install
  script:
    - pip install -r task-testing-python/requirements.txt
    - pip install flake8
  tags:
    - common
    - cpu

TestCode:
  stage: test
  script:
    - pip install -r task-testing-python/requirements.txt
    - PYTHONPATH=task-testing-python/src pytest --cov=task-testing-python/src --junitxml=report.xml task-testing-python/tests
  tags:
    - common
    - cpu
  artifacts:
    paths:
      - report.xml
    when: always
    reports:
      junit: report.xml


LintCode:
  stage: test
  script:
    - pip install flake8
    - flake8 task-testing-python/src
  tags:
    - common
    - cpu

#       - build/*
