version: '3.9'

services:
  db:
    image: postgres:16.3-alpine3.19
    env_file:
      - db/.db.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 80s

  backend:
    build:
      context: backend
    environment:
      - DB_HOST=db:5432
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
